name: curemap-communication-service

services:
  app_database:
    image: postgres:latest
    container_name: curemap-communication-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  app_redis:
    image: redis:latest
    container_name: curemap-communication-cache
    ports:
      - "6379:6379"
  app_rabbit:
    image: rabbitmq:3.13-management
    container_name: curemap-rabbitmq-messaging
    ports:
      - "15672:15672"
      - "5672:5672"